# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2010-2015 Intel Corporation

include $(RTE_SDK)/mk/rte.vars.mk

NETSWIFT_VERSION=$(shell printf "%02d.%02d" $(CONFIG_RTE_VER_YEAR) $(CONFIG_RTE_VER_MONTH))
DIRS-y += $(NETSWIFT_VERSION)

include $(RTE_SDK)/mk/rte.subdir.mk
