// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p4/tmp/p4config.proto

#ifndef PROTOBUF_INCLUDED_p4_2ftmp_2fp4config_2eproto
#define PROTOBUF_INCLUDED_p4_2ftmp_2fp4config_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_p4_2ftmp_2fp4config_2eproto 

namespace protobuf_p4_2ftmp_2fp4config_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_p4_2ftmp_2fp4config_2eproto
namespace p4 {
namespace tmp {
class P4DeviceConfig;
class P4DeviceConfigDefaultTypeInternal;
extern P4DeviceConfigDefaultTypeInternal _P4DeviceConfig_default_instance_;
class P4DeviceConfig_Extras;
class P4DeviceConfig_ExtrasDefaultTypeInternal;
extern P4DeviceConfig_ExtrasDefaultTypeInternal _P4DeviceConfig_Extras_default_instance_;
class P4DeviceConfig_Extras_KvEntry_DoNotUse;
class P4DeviceConfig_Extras_KvEntry_DoNotUseDefaultTypeInternal;
extern P4DeviceConfig_Extras_KvEntry_DoNotUseDefaultTypeInternal _P4DeviceConfig_Extras_KvEntry_DoNotUse_default_instance_;
}  // namespace tmp
}  // namespace p4
namespace google {
namespace protobuf {
template<> ::p4::tmp::P4DeviceConfig* Arena::CreateMaybeMessage<::p4::tmp::P4DeviceConfig>(Arena*);
template<> ::p4::tmp::P4DeviceConfig_Extras* Arena::CreateMaybeMessage<::p4::tmp::P4DeviceConfig_Extras>(Arena*);
template<> ::p4::tmp::P4DeviceConfig_Extras_KvEntry_DoNotUse* Arena::CreateMaybeMessage<::p4::tmp::P4DeviceConfig_Extras_KvEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace p4 {
namespace tmp {

// ===================================================================

class P4DeviceConfig_Extras_KvEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<P4DeviceConfig_Extras_KvEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<P4DeviceConfig_Extras_KvEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  P4DeviceConfig_Extras_KvEntry_DoNotUse();
  P4DeviceConfig_Extras_KvEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const P4DeviceConfig_Extras_KvEntry_DoNotUse& other);
  static const P4DeviceConfig_Extras_KvEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const P4DeviceConfig_Extras_KvEntry_DoNotUse*>(&_P4DeviceConfig_Extras_KvEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class P4DeviceConfig_Extras : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p4.tmp.P4DeviceConfig.Extras) */ {
 public:
  P4DeviceConfig_Extras();
  virtual ~P4DeviceConfig_Extras();

  P4DeviceConfig_Extras(const P4DeviceConfig_Extras& from);

  inline P4DeviceConfig_Extras& operator=(const P4DeviceConfig_Extras& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  P4DeviceConfig_Extras(P4DeviceConfig_Extras&& from) noexcept
    : P4DeviceConfig_Extras() {
    *this = ::std::move(from);
  }

  inline P4DeviceConfig_Extras& operator=(P4DeviceConfig_Extras&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const P4DeviceConfig_Extras& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const P4DeviceConfig_Extras* internal_default_instance() {
    return reinterpret_cast<const P4DeviceConfig_Extras*>(
               &_P4DeviceConfig_Extras_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(P4DeviceConfig_Extras* other);
  friend void swap(P4DeviceConfig_Extras& a, P4DeviceConfig_Extras& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline P4DeviceConfig_Extras* New() const final {
    return CreateMaybeMessage<P4DeviceConfig_Extras>(NULL);
  }

  P4DeviceConfig_Extras* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<P4DeviceConfig_Extras>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const P4DeviceConfig_Extras& from);
  void MergeFrom(const P4DeviceConfig_Extras& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P4DeviceConfig_Extras* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> kv = 1;
  int kv_size() const;
  void clear_kv();
  static const int kKvFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      kv() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_kv();

  // @@protoc_insertion_point(class_scope:p4.tmp.P4DeviceConfig.Extras)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      P4DeviceConfig_Extras_KvEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > kv_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_p4_2ftmp_2fp4config_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class P4DeviceConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:p4.tmp.P4DeviceConfig) */ {
 public:
  P4DeviceConfig();
  virtual ~P4DeviceConfig();

  P4DeviceConfig(const P4DeviceConfig& from);

  inline P4DeviceConfig& operator=(const P4DeviceConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  P4DeviceConfig(P4DeviceConfig&& from) noexcept
    : P4DeviceConfig() {
    *this = ::std::move(from);
  }

  inline P4DeviceConfig& operator=(P4DeviceConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const P4DeviceConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const P4DeviceConfig* internal_default_instance() {
    return reinterpret_cast<const P4DeviceConfig*>(
               &_P4DeviceConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(P4DeviceConfig* other);
  friend void swap(P4DeviceConfig& a, P4DeviceConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline P4DeviceConfig* New() const final {
    return CreateMaybeMessage<P4DeviceConfig>(NULL);
  }

  P4DeviceConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<P4DeviceConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const P4DeviceConfig& from);
  void MergeFrom(const P4DeviceConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(P4DeviceConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef P4DeviceConfig_Extras Extras;

  // accessors -------------------------------------------------------

  // bytes device_data = 3;
  void clear_device_data();
  static const int kDeviceDataFieldNumber = 3;
  const ::std::string& device_data() const;
  void set_device_data(const ::std::string& value);
  #if LANG_CXX11
  void set_device_data(::std::string&& value);
  #endif
  void set_device_data(const char* value);
  void set_device_data(const void* value, size_t size);
  ::std::string* mutable_device_data();
  ::std::string* release_device_data();
  void set_allocated_device_data(::std::string* device_data);

  // .p4.tmp.P4DeviceConfig.Extras extras = 2;
  bool has_extras() const;
  void clear_extras();
  static const int kExtrasFieldNumber = 2;
  private:
  const ::p4::tmp::P4DeviceConfig_Extras& _internal_extras() const;
  public:
  const ::p4::tmp::P4DeviceConfig_Extras& extras() const;
  ::p4::tmp::P4DeviceConfig_Extras* release_extras();
  ::p4::tmp::P4DeviceConfig_Extras* mutable_extras();
  void set_allocated_extras(::p4::tmp::P4DeviceConfig_Extras* extras);

  // bool reassign = 1;
  void clear_reassign();
  static const int kReassignFieldNumber = 1;
  bool reassign() const;
  void set_reassign(bool value);

  // @@protoc_insertion_point(class_scope:p4.tmp.P4DeviceConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_data_;
  ::p4::tmp::P4DeviceConfig_Extras* extras_;
  bool reassign_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_p4_2ftmp_2fp4config_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// P4DeviceConfig_Extras

// map<string, string> kv = 1;
inline int P4DeviceConfig_Extras::kv_size() const {
  return kv_.size();
}
inline void P4DeviceConfig_Extras::clear_kv() {
  kv_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
P4DeviceConfig_Extras::kv() const {
  // @@protoc_insertion_point(field_map:p4.tmp.P4DeviceConfig.Extras.kv)
  return kv_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
P4DeviceConfig_Extras::mutable_kv() {
  // @@protoc_insertion_point(field_mutable_map:p4.tmp.P4DeviceConfig.Extras.kv)
  return kv_.MutableMap();
}

// -------------------------------------------------------------------

// P4DeviceConfig

// bool reassign = 1;
inline void P4DeviceConfig::clear_reassign() {
  reassign_ = false;
}
inline bool P4DeviceConfig::reassign() const {
  // @@protoc_insertion_point(field_get:p4.tmp.P4DeviceConfig.reassign)
  return reassign_;
}
inline void P4DeviceConfig::set_reassign(bool value) {
  
  reassign_ = value;
  // @@protoc_insertion_point(field_set:p4.tmp.P4DeviceConfig.reassign)
}

// .p4.tmp.P4DeviceConfig.Extras extras = 2;
inline bool P4DeviceConfig::has_extras() const {
  return this != internal_default_instance() && extras_ != NULL;
}
inline void P4DeviceConfig::clear_extras() {
  if (GetArenaNoVirtual() == NULL && extras_ != NULL) {
    delete extras_;
  }
  extras_ = NULL;
}
inline const ::p4::tmp::P4DeviceConfig_Extras& P4DeviceConfig::_internal_extras() const {
  return *extras_;
}
inline const ::p4::tmp::P4DeviceConfig_Extras& P4DeviceConfig::extras() const {
  const ::p4::tmp::P4DeviceConfig_Extras* p = extras_;
  // @@protoc_insertion_point(field_get:p4.tmp.P4DeviceConfig.extras)
  return p != NULL ? *p : *reinterpret_cast<const ::p4::tmp::P4DeviceConfig_Extras*>(
      &::p4::tmp::_P4DeviceConfig_Extras_default_instance_);
}
inline ::p4::tmp::P4DeviceConfig_Extras* P4DeviceConfig::release_extras() {
  // @@protoc_insertion_point(field_release:p4.tmp.P4DeviceConfig.extras)
  
  ::p4::tmp::P4DeviceConfig_Extras* temp = extras_;
  extras_ = NULL;
  return temp;
}
inline ::p4::tmp::P4DeviceConfig_Extras* P4DeviceConfig::mutable_extras() {
  
  if (extras_ == NULL) {
    auto* p = CreateMaybeMessage<::p4::tmp::P4DeviceConfig_Extras>(GetArenaNoVirtual());
    extras_ = p;
  }
  // @@protoc_insertion_point(field_mutable:p4.tmp.P4DeviceConfig.extras)
  return extras_;
}
inline void P4DeviceConfig::set_allocated_extras(::p4::tmp::P4DeviceConfig_Extras* extras) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete extras_;
  }
  if (extras) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      extras = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, extras, submessage_arena);
    }
    
  } else {
    
  }
  extras_ = extras;
  // @@protoc_insertion_point(field_set_allocated:p4.tmp.P4DeviceConfig.extras)
}

// bytes device_data = 3;
inline void P4DeviceConfig::clear_device_data() {
  device_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& P4DeviceConfig::device_data() const {
  // @@protoc_insertion_point(field_get:p4.tmp.P4DeviceConfig.device_data)
  return device_data_.GetNoArena();
}
inline void P4DeviceConfig::set_device_data(const ::std::string& value) {
  
  device_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:p4.tmp.P4DeviceConfig.device_data)
}
#if LANG_CXX11
inline void P4DeviceConfig::set_device_data(::std::string&& value) {
  
  device_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:p4.tmp.P4DeviceConfig.device_data)
}
#endif
inline void P4DeviceConfig::set_device_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:p4.tmp.P4DeviceConfig.device_data)
}
inline void P4DeviceConfig::set_device_data(const void* value, size_t size) {
  
  device_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:p4.tmp.P4DeviceConfig.device_data)
}
inline ::std::string* P4DeviceConfig::mutable_device_data() {
  
  // @@protoc_insertion_point(field_mutable:p4.tmp.P4DeviceConfig.device_data)
  return device_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* P4DeviceConfig::release_device_data() {
  // @@protoc_insertion_point(field_release:p4.tmp.P4DeviceConfig.device_data)
  
  return device_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void P4DeviceConfig::set_allocated_device_data(::std::string* device_data) {
  if (device_data != NULL) {
    
  } else {
    
  }
  device_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_data);
  // @@protoc_insertion_point(field_set_allocated:p4.tmp.P4DeviceConfig.device_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tmp
}  // namespace p4

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_p4_2ftmp_2fp4config_2eproto
